# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
{{- if .Values.wso2.apk.cp.enabled }}
apiVersion: "gateway.networking.k8s.io/v1beta1"
kind: "HTTPRoute"
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-httproute
  namespace: {{ .Release.Namespace }}
  labels:
    api-name: "admin-domain-service"
    api-version: "1.0.0"
spec:
  hostnames:
  - "{{ .Values.wso2.apk.listener.hostname | default "api.am.wso2.com"}}"
  rules:
  - matches:
    - path:
        type: "RegularExpression"
        value: "/policies/search"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/application-rate-plans"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/application-rate-plans"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/application-rate-plans/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/application-rate-plans/(.*)"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/application-rate-plans/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/business-plans"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/business-plans"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/business-plans/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/business-plans/(.*)"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/business-plans/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/throttling/policies/advanced"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/throttling/policies/advanced"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/throttling/policies/advanced/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/throttling/policies/advanced/(.*)"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/throttling/policies/advanced/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/throttling/policies/export"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/throttling/policies/import"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/deny-policies"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/deny-policies"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/deny-policies/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/deny-policies/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/deny-policies/(.*)"
      method: "PATCH"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/applications"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/applications/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/applications/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/applications/(.*)/change-owner"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/environments"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/environments"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/environments/(.*)"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/environments/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/bot-detection-data"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/monetization/publish-usage"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/monetization/publish-usage/status"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/workflows"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/workflows/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/workflows/update-workflow-status"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/tenant-info/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/custom-urls/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api-categories"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api-categories"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api-categories/(.*)"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api-categories/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/settings"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/system-scopes/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/system-scopes"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/system-scopes"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/system-scopes/role-aliases"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/system-scopes/role-aliases"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/roles/(.*)"
      method: "HEAD"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/tenant-theme"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/tenant-theme"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/tenant-config"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/tenant-config"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/tenant-config-schema"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/key-managers"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/key-managers"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/key-managers/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/key-managers/(.*)"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/key-managers/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/key-managers/discover"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "PathPrefix"
        value: "/organizations"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/organization-info"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-admin-ds-backend
  parentRefs:
  - group: "gateway.networking.k8s.io"
    kind: "Gateway"
    name: "default"
    sectionName: "httpslistener"
{{- end -}}
