{{- if or .Values.wso2.apk.dp.enabled .Values.wso2.apk.cp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-common-log-conf
  namespace: {{ .Release.Namespace }}
data:
  config.toml: | 
    [commoncontroller]
      {{- if and .Values.wso2.apk.dp.environment .Values.wso2.apk.dp.environment.name }}
      environment = "{{ .Values.wso2.apk.dp.environment.name }}"
      {{- end }}
    [commoncontroller.server]
      label = "ratelimiter"
    {{ if and .Values.wso2.apk.dp.commonController.configs .Values.wso2.apk.dp.commonController.configs.apiNamespaces }}
    [commoncontroller.operator]
      namespaces = [{{ include "commaJoinedQuotedList" .Values.wso2.apk.dp.commonController.configs.apiNamespaces}}]
    {{ end}}  
    [commoncontroller.keystore]
      certPath = "/home/wso2/security/keystore/commoncontroller.crt"
      keyPath = "/home/wso2/security/keystore/commoncontroller.key"

    [commoncontroller.truststore]
      location = "/home/wso2/security/truststore"

    [commoncontroller.redis]
    {{- if .Values.wso2.apk.dp.commonController.deployment.redis }}
      host = "{{ .Values.wso2.apk.dp.commonController.deployment.redis.host | default "redis-master" }}"
      port = "{{ .Values.wso2.apk.dp.commonController.deployment.redis.port | default "6379" }}"
      username = "{{ .Values.wso2.apk.dp.commonController.deployment.redis.username | default "default" }}"
      password = "{{ .Values.wso2.apk.dp.commonController.deployment.redis.password | default "" }}"
      userCertPath = "{{ .Values.wso2.apk.dp.commonController.deployment.redis.userCertPath | default "/home/wso2/security/keystore/commoncontroller.crt" }}"
      userKeyPath = "{{ .Values.wso2.apk.dp.commonController.deployment.redis.userKeyPath | default "/home/wso2/security/keystore/commoncontroller.key" }}"
      cACertPath = "{{ .Values.wso2.apk.dp.commonController.deployment.redis.redisCaCertPath | default "/home/wso2/security/keystore/commoncontroller.crt" }}"
      tlsEnabled = {{ .Values.wso2.apk.dp.commonController.deployment.redis.tlsEnabled | default false }}
      revokedTokenChannel = "{{ .Values.wso2.apk.dp.commonController.deployment.redis.channelName | default "wso2-apk-revoked-tokens-channel" }}"
    {{- else }}
      host = "redis-master"
      port = "6379"
      username = "default"
      password = ""
      userCertPath = "/home/wso2/security/keystore/commoncontroller.crt"
      userKeyPath = "/home/wso2/security/keystore/commoncontroller.key"
      cACertPath = "/home/wso2/security/keystore/commoncontroller.crt"
      tlsEnabled = false
      revokedTokenChannel = "wso2-apk-revoked-tokens-channel"
    {{- end }}
    [commoncontroller.sts]
      authKeyPath = "/home/wso2/security/sts/auth_key.txt"
      authKeyHeader = "stsAuthKey"
    
    [commoncontroller.webServer]
      port = 9543

{{- end -}}
